apiVersion: v1
kind: Namespace
metadata:
  name: shop-platform
  labels:
    name: shop-platform
    # Enforces Pod Security Standards — "restricted" is the strictest profile
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
